apply plugin: 'com.android.application'
//apply plugin: 'me.tatarka.retrolambda'
apply from: '../findbugs.gradle'


android {
  compileSdkVersion rootProject.ext.compileSdkVersion
  buildToolsVersion rootProject.ext.buildToolsVersion

  compileOptions {
    // For retrolambda support
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  defaultConfig {
    applicationId "com.hannesdorfmann.mosby3.sample.mvi"
    minSdkVersion 16
    targetSdkVersion rootProject.ext.targetSdk
    versionName project.VERSION_NAME
    versionCode Integer.parseInt(project.VERSION_CODE)
  }

  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }

  lintOptions {
    abortOnError false
  }

  packagingOptions {
    exclude 'META-INF/services/javax.annotation.processing.Processor'
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/NOTICE'
    exclude 'META-INF/MANIFEST.MF'
    exclude 'META-INF/rxjava.properties'
    exclude 'LICENSE'
    exclude 'NOTICE'
  }
}

dependencies {

  def retrofitVersion = '2.2.0'
  def rxbindingVersion = '3.1.0'
  def okHttpVersion = '3.6.0'


  implementation project(':mvi')

  implementation 'androidx.appcompat:appcompat:' + rootProject.ext.appcompatVersion
  implementation 'androidx.recyclerview:recyclerview:' + rootProject.ext.recyclerViewVersion
  implementation 'androidx.transition:transition:' + rootProject.ext.transitionVersion
  implementation 'androidx.cardview:cardview:' + rootProject.ext.cardViewVersion
  implementation 'com.google.android.material:material:' + rootProject.ext.materialVersion
  implementation 'androidx.core:core:' + rootProject.ext.androidxCoreVersion
  implementation 'androidx.drawerlayout:drawerlayout:' + rootProject.ext.drawerLayoutVersion
  implementation 'androidx.swiperefreshlayout:swiperefreshlayout:' + rootProject.ext.swipeRefreshLayoutVersion

  implementation 'com.jakewharton.timber:timber:4.5.0'

  implementation 'com.squareup.okhttp3:okhttp:' + okHttpVersion
  implementation 'com.squareup.okhttp3:logging-interceptor:' + okHttpVersion


  testImplementation 'junit:junit:' + rootProject.ext.junitVersion
  testImplementation 'org.mockito:mockito-core:' + rootProject.ext.mockitoVersion
  testImplementation 'com.squareup.okhttp3:mockwebserver:' + okHttpVersion


  compileOnly 'com.google.code.findbugs:annotations:3.0.0'

  implementation "com.squareup.retrofit2:retrofit:$retrofitVersion"
  implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofitVersion"
  implementation "com.squareup.retrofit2:converter-moshi:$retrofitVersion"

  implementation 'com.jakewharton:butterknife:'+rootProject.ext.butterknifeVersion
  annotationProcessor 'com.jakewharton:butterknife-compiler:' + rootProject.ext.butterknifeVersion

  implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
  implementation 'com.github.bumptech.glide:glide:4.16.0'

  debugImplementation 'com.squareup.leakcanary:leakcanary-android:' + rootProject.ext.leakcanaryVersion
  releaseImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:' + rootProject.ext.leakcanaryVersion
  testImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:' + rootProject.ext.leakcanaryVersion

  implementation "com.jakewharton.rxbinding3:rxbinding:$rxbindingVersion"
  implementation "com.jakewharton.rxbinding3:rxbinding-swiperefreshlayout:$rxbindingVersion"
  implementation "com.jakewharton.rxbinding3:rxbinding-material:$rxbindingVersion"
  implementation "com.jakewharton.rxbinding3:rxbinding-recyclerview:$rxbindingVersion"
}
