apply plugin: 'com.android.application'
apply from: '../findbugs.gradle'

android {
  compileSdkVersion rootProject.ext.compileSdkVersion
  buildToolsVersion rootProject.ext.buildToolsVersion

  compileOptions {
    sourceCompatibility rootProject.ext.javaSourceCompatibility
    targetCompatibility rootProject.ext.javaTargetCompatibility
  }

  defaultConfig {
    applicationId "com.hannesdorfmann.mosby.sample"
    minSdkVersion rootProject.ext.minSdk
    targetSdkVersion rootProject.ext.targetSdk
    versionName project.VERSION_NAME
    versionCode Integer.parseInt(project.VERSION_CODE)
  }
  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }
}


dependencies {
  implementation project(':mvp-lce')
  implementation project(':mvp-queuing-presenter')

  implementation 'com.google.android.material:material:' + rootProject.ext.materialVersion
  implementation 'androidx.recyclerview:recyclerview:' + rootProject.ext.recyclerViewVersion
  implementation 'androidx.appcompat:appcompat:' + rootProject.ext.appcompatVersion
  implementation 'androidx.swiperefreshlayout:swiperefreshlayout:' + rootProject.ext.swipeRefreshLayoutVersion
  implementation 'androidx.viewpager:viewpager:' + rootProject.ext.viewPagerVersion


  implementation 'com.jakewharton:butterknife:'+rootProject.ext.butterknifeVersion
  annotationProcessor 'com.jakewharton:butterknife-compiler:' + rootProject.ext.butterknifeVersion

  implementation 'com.hannesdorfmann.parcelableplease:annotation:' + rootProject.ext.parcelablepleaseVersion
  annotationProcessor 'com.hannesdorfmann.parcelableplease:processor:' + rootProject.ext.parcelablepleaseVersion


  implementation 'com.squareup.leakcanary:leakcanary-android:'+ rootProject.ext.leakcanaryVersion
}
